language: node_js
node_js:
  - 12.18.3
before_install:
  - yarn install
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - backend@hakbong.me
    on_success: change # default: change
    on_failure: always # default: always
  slack:
    secure: secure: "ap1I0Zcyvp93zXKaTPy92/E+a7SiqOyjqW0x+pOWvscJCOBvkoOWXKFrkX8oHewRm51Ga3ig0nkqjjo3zC5Hpq1RZwoX1DBsBGpdQtMJdi9OwtEsBXPKr86fVnlT0h2pUTsgNbLn3w2LTz/5oPEFvhfmBaXRvgLjgEE8YBbo77sNsERFPIO9cWDIcfBLzS62Fr5+lT9fWo3DProgwlKNCs1YH6EBm9gxUBCvpMBdCV1PFaw++EsmDf5f63sqfkFb/fk0UFiV2mSSu7zAMevNBy0RT0ydpBHzfGPqZgoDkOtNxpuYmlmig4AcHbsyHm3LGWL94QZpUctbHoLal1D/qpQTupHO/kBWroQ47jU4TFjN0XS//MBvKiCuXudKMRwpp1fmM5V4sVhxpQ9aWuBEJwZdP+nD92LBGZMX/dHv4921ShutG65OtWkdYqNbgy+wH3T26rMGmT4037UlIAwpIGlwzzEElCeKkjyWjqhOOJWgJLLGzr5wB6R31inNic9YOPaCaKv9nNoPflM78AmjJjsIuvM7tFd6ja+/+JCFXGKrRLaDUNGhy2gDBsgPJVshCOwizEsCcpeT5r5ScLhpbFUkM6Cuytz3to64cscIRf/qP7VVDSmnhNq5i8UoWFfqJGhYvowiebVcnMKZoihVA7DgtlFPat7fOo/y5gnNrkY="
